name: 3dmolgen
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - cloudpickle==3.1.1
      - datamol==0.12.0
      - loguru==0.7.3
      - numpy==2.2.6
      - ogb==1.3.6
      - pandas==2.2.3
      - posebusters==0.4.4
      - pytest==8.4.0
      - PyYAML==6.0.2
      - rdkit==2024.9.4
      - scipy==1.15.3
      - submitit==1.5.3
      - torch==2.7.0
      - tqdm==4.67.1
      - transformers==4.52.4
