validation:
  enable_numerical_validation: true
  use_dataset_prompts: true
  validation_batch_size: 2048
  eval_steps: 200
dataset:
  dataset_path: /data/molgen/cartesian_v5_binned_grouped/grouped_binned_run1/train_smiles.jsonl
  smiles_mapping_path: /data/molgen/cartesian_v5_binned_grouped/grouped_binned_run1/train_smiles_to_pickle.json
device:
  device_type: local
  num_gpus: 1
generation:
  do_sample: true
  max_completion_length: 4096
  num_return_sequences: 1
  repetition_penalty: 1.0
  temperature: 1.0
grpo:
  output_base_dir: ./grpo_outputs
  checkpoint_base_dir: /home/chem-project/checkpoints/conf_grpo
  reward_strategy: fbeta
  learning_rate: 6.0e-05
  temperature: 1.0
  num_generations: 8
  grad_acc_steps: 1
  per_device_batch_size: 2
  scheduler: cosine
  importance_sampling_level: sequence
  adam_beta1: 0.9
  adam_beta2: 0.95
  weight_decay: 0.0
  warmup_ratio: 0.03
  max_grad_norm: 1.0
  beta: 0
  seed: 1
  max_ground_truths: 30
  max_steps: 2000
  sampling_top_k: 50
  enable_conformer_logits_processor: true
  target_conformers: 8
  fbeta_use_binned_decoder: true
  fbeta_beta: 1.5
  fbeta_gamma: 1.5
  fbeta_delta: 0.75
  fbeta_dup_rmsd_tau: 0.3
  fbeta_recall_ref_sample: 12
  fbeta_min_valid_to_score: 0
  fbeta_drop_if_valid_lt: 3
  fbeta_warmup_lambda: 0.1
  fbeta_warmup_sigma: 0.75
  log_success_sample_every: 10
  log_success_sample_chars: 400
  log_debug_sample_every: 10
  log_debug_sample_chars: 400
  log_full_sample_every: 10
model:
  checkpoint_path: /home/chem-project/checkpoints/qwen3_06b/260123-0058-1aea-qwen3_06b_pre_4e_8e-4_binned_grouped/step-34000-hf
  tokenizer_path: src/molgen3D/training/tokenizers/Qwen3_tokenizer_custom
  mol_tags:
  - '[SMILES]'
  - '[/SMILES]'
  conf_tags:
  - '[CONFORMER]'
  - '[/CONFORMER]'
  pad_token: <|endoftext|>
  dtype: bf16
processing:
  eos_token_id: 151672
run:
  name: qwen3_fbeta_binned
trainer:
  attn_implementation: sdpa
